parameters:
#    newstore_magasin.example.class: Newstore\MagasinBundle\Example

services:
#    newstore_magasin.example:
#        class: %newstore_magasin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
