<?php

namespace Newstore\MagasinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends EntityRepository
{
}
