parameters:
#    newstore_fournisseur.example.class: Newstore\FournisseurBundle\Example

services:
#    newstore_fournisseur.example:
#        class: %newstore_fournisseur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
