parameters:
#    newstore_zone.example.class: Newstore\ZoneBundle\Example

services:
#    newstore_zone.example:
#        class: %newstore_zone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
