parameters:
#    newstore_livraison.example.class: Newstore\LivraisonBundle\Example

services:
#    newstore_livraison.example:
#        class: %newstore_livraison.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
