parameters:
#    new_store_categorie.example.class: NewStore\CategorieBundle\Example

services:
#    new_store_categorie.example:
#        class: %new_store_categorie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
