<?php

namespace Newstore\CamionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CamionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamionRepository extends EntityRepository
{
}
