parameters:
#    newstore_camion.example.class: Newstore\CamionBundle\Example

services:
#    newstore_camion.example:
#        class: %newstore_camion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
